### ISSUE TITLE
en_us.lang Missing on Forge 1.12 - 14.21.1.2387 Server

### ISSUE THREAD

**Issue by TheFloydman** [Olafski/FastLeafDecay#10]
I am getting the following error when using Fast Leaf Decay on a Forge 1.12 - 14.21.1.2387 Server:

thread/WARN [FML]: Missing English translation for fastleafdecay: assets/fastleafdecay/lang/en_us.lang
11.08 18:25:40 [Server] INFO java.io.FileNotFoundException: assets/fastleafdecay/lang/en_us.lang

This prevents the server from starting.

**Comment by Olafski** [comment]
Hey TheFloydman, thanks for your report.

That file should not have to exist, so I am not sure why you're getting this error.

I have tried to reproduce this, but the server starts fine. I can also connect and notice that the mod is loaded. This is with version 13 of the mod, on the forge server you mentioned.

Could you tell me if you have any other mods or anything else that could interfere?

**Comment by TheFloydman** [comment]
Ah, I was using the newest v14. v13 does indeed work with that Forge version. Thank you for the clarification.

**Comment by Olafski** [comment]
Thanks for the response and glad to hear it! 

Version 14 is for Minecraft 1.12.1. Should work with that, but not with 1.12.
