### ISSUE TITLE
Mod not marked as supporting 1.12.2

### ISSUE THREAD

**Issue by C0rn3j** [Olafski/FastLeafDecay#14]
Hi, this mod is not marked as 1.12.2. I assume it works on that version since there's a 1.12.1 marked version.

https://minecraft.curseforge.com/projects/fast-leaf-decay/files
please mark the 1.12.1 file as 1.12.2 too.

Unless it actually doesn't work for .2, in that case feel free to close this issue, but mods in general seem to work that way ^^

This "broke" my updater script.

**Comment by Olafski** [comment]
Done, thank you. :)
