### ISSUE TITLE
[Suggestion] Add to CurseForge

### ISSUE THREAD

**Issue by SnowShock35** [Olafski/FastLeafDecay#2]
Hi @Olafski 

I was wondering if you are able to add fast leaf decay to CurseForge. Would be extremely helpful if you could. Thanks -Snow ;)

**Comment by Olafski** [comment]
Hello SnowShock35,

Thanks for the suggestion. I am currently not interested in having my addon on the Curse Client.

Olafski

**Comment by SnowShock35** [comment]
Rather blunt to the point answer, but understandable ;)
-Snow

**Comment by Olafski** [comment]
Been working on the addon a bit, and I have after all decided to put the releases on Curse: http://minecraft.curseforge.com/mc-mods/230976-fastleafdecay

Hope this helps :)

**Comment by SnowShock35** [comment]
Awesome mate! Thx u so so much. I can't tell u how much this helps and I really do appreciate you putting it on there ;) -Snow
