### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by winnetrie83** [Olafski/FastLeafDecay#20]
I see you closed all other cascading worldgen lag issues, but none has been solved.
The problem persist.
It is commonly recommended to remove any mod that causes cascading worldgen lag and should be a main priority to fix.
Ofcourse no 1 has to tell you what to do and if you feel this isue is not an isue for you…...well 
eventually people will stop using bad coded mods

**Comment by Olafski** [comment]
Hello winnetrie83,

I know for a fact my mod does not cause any worldgen. However, if other mods cause (cascading) worldgen which contains trees that are "too large", my mod will do its thing as soon as their leaves start decaying.

If you have an actual reproducable issue, please feel free to open another ticket.
