### ISSUE TITLE
Forge breaks your mod.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [Olafski/FastLeafDecay#26]
Forge 1.15.1 - 20.0.51 Changlog "Rename ModConfigEvent.ConfigReloading to ModConfigEvent.Reloading"

Breaks your mod. Please update. Thanks.

**Comment by Olafski** [comment]
Quite inconvenient that they keep doing this.. ;)

Thanks for the reminder, v20 should fix it!
