### ISSUE TITLE
Crash with Bloomful

### ISSUE THREAD

**Issue by bageldotjpg** [Olafski/FastLeafDecay#32]
Fast Leaf Decay 1.15 v20
Bloomful 1.3

**Crash Report:** 
[crash-2020-03-21_12.10.44-server.txt](https://github.com/Olafski/FastLeafDecay/files/4363421/crash-2020-03-21_12.10.44-server.txt)

**Comment by Olafski** [comment]
This should be fixed with v21, available on CurseForge. If it's not, please open another issue.
