### ISSUE TITLE
Vanilla Decay Times

### ISSUE THREAD

**Issue by TheUntamed** [Olafski/FastLeafDecay#34]
Not a Issue, Just a question: Do you know the mc vanilla default min and max values for leaves to decay?

**Comment by Olafski** [comment]
Hey TheUntamed. This is hard to say, as vanilla decay rates are not governed by min/max but by chance. Theoretically all leaves in a tree could be gone very quickly, or one leaf could stay around forever. So I can't really give you good numbers.
