### ISSUE TITLE
[1.15.2] Config is no longer global

### ISSUE THREAD

**Issue by Insane96** [Olafski/FastLeafDecay#36]
There's no config for the mod as v22

**Comment by Olafski** [comment]
Hey Insane96,

The Forge config has moved, I'm not sure since when. It now resides inside your world folder. So if you look in `minecraftfolder\saves\[world_name]\serverconfig`, you should find a file named `fastleafdecay-server.toml` which contains the configuration settings.

**Comment by Insane96** [comment]
But this would require to edit the config for each world

Il Mer 8 Apr 2020, 12:19 Olaf Keijsers <notifications@github.com> ha
scritto:

**Comment by Olafski** [comment]
Yes, I believe so. I have no real idea how to make the config global again, I believe this is an intentional choice by the Forge team.

**Comment by Insane96** [comment]
Doesn't seem that hard. Check
https://github.com/Insane96/VulcaniteMod/blob/1.15.2/src/main/java/insane96mcp/vulcanite/Vulcanite.java#L25

https://github.com/Insane96/VulcaniteMod/blob/1.15.2/src/main/java/insane96mcp/vulcanite/setup/ModConfig.java

**Comment by Olafski** [comment]
Does not seem like an issue to me.

**Comment by Maxwelljones** [comment]
Sorry to re-open this:
I am mod-packer. I don't want to provide a world-save together with the modpack. How can I implement a global config for FLD for every world - not only my test world?
