### ISSUE TITLE
Unusual interactions with EE3 (Mod version 1.0)

### ISSUE THREAD

**Issue by xsneakyxsimx** [Olafski/FastLeafDecay#4]
When used with Equivalent Exchange 3 (0.3.507), it seems to remove EMC values and makes vanilla dyes (except for Lapis Lazuli), dyed variants of wool, hardened clay, glass (block and panes), cobblestone walls, and certain tools, as well as items from Progressive Automation unable to be learned.  May have altered more but those were the items I noted as being different when the mod was active, and were restored when it was deactivated.  Also making a similar post onto EE3's Issues page.

**Comment by Olafski** [comment]
Hey xsneakyxsimx,

Are you absolutely sure that it's FastLeafDecay causing these issues? While I'm always willing to investigate, this does sound rather unlikely considering I don't change a single item (only blocks, and then only event handlers on those).

I'll check out the post you made on EE3's page to see if Pahimar has some idea.

**Comment by Olafski** [comment]
I just did a little testing and found that with or without FastLeafDecay enabled, the first few items I got in a new world did have an EMC value (at least when I pressed shift while hovering the items). Could you tell me what isn't working for you?

**Comment by xsneakyxsimx** [comment]
I've just recorded a small video showing the EMC values on particular items both with Fast Leaf Decay enabled and disabled, all other mods that I use were not altered in it.  I can publish it to YouTube as a Private video and send you the link so you may see for yourself.

**Comment by Olafski** [comment]
Please do. In my test, I only used EE3, FastLeafDecay and NEI by the way. Could you also try to reproduce it with that setup?

**Comment by xsneakyxsimx** [comment]
I can do that, may be helpful in case there is another mod or mods also involved.

Also, the video in question that just finished uploading: https://youtu.be/CLzyerLAq8w

**Comment by Olafski** [comment]
Interesting. That does seem to imply my mod is at least involved in the issue... I'll try again tonight with my test setup, looking at the same blocks you did. I made a new world, so I just checked the first few blocks I could gather (dirt, sugar cane, seeds).

**Comment by Olafski** [comment]
I checked again: all wool types, dyes, cobblestone, et cetera still have EMC values for me.

**Comment by xsneakyxsimx** [comment]
My apologies for not responding sooner.  We're in the midst of a kitchen reno so it's a little 'all hands on deck'  I've thus far not been able to test with just EE3, FastLeafDecay and NEI, in part due to time, and in part due to an inexperience with adding mods to vanilla myself, just into modpack.

When you were watching the video where I was showing what mods were enabled and running, were there any that may have caught your attention for any reason that could offer a possible explanation?

**Comment by Olafski** [comment]
I just checked the video again, can't see any mods that I would expect to interact badly with FLD. 

Did you get around to trying with only FLD and EE3?
