### ISSUE TITLE
1.16.1 forge server console spam ??

### ISSUE THREAD

**Issue by SDUBZ** [Olafski/FastLeafDecay#40]
[STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:56]: == notifyneighbours, air, block = Block{minecraft:air}
←[m←[32m[19:44:48] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:andesite}
←[m←[32m[19:44:48] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:cave_air}
←[m←[32m[19:44:48] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:andesite}
←[m←[32m[19:44:48] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:cave_air}
←[m←[32m[19:44:48] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:air}
←[m←[32m[19:44:48] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:andesite}
←[m←[32m[19:44:56] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:56]: == notifyneighbours, air, block = Block{minecraft:air}
←[m←[32m[19:44:56] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:farmland}
←[m←[32m[19:44:56] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:air}
←[m←[32m[19:44:56] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:carrots}
←[m←[32m[19:44:56] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:carrots}
←[m←[32m[19:44:56] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:air}
←[m←[32m[19:44:56] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:carrots}
←[m←[32m[19:44:57] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:56]: == notifyneighbours, air, block = Block{minecraft:air}
←[m←[32m[19:44:57] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:farmland}
←[m←[32m[19:44:57] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:air}
←[m←[32m[19:44:57] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:carrots}
←[m←[32m[19:44:57] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:air}
←[m←[32m[19:44:57] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:air}
←[m←[32m[19:44:57] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:carrots}
←[m←[32m[19:47:24] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:56]: == notifyneighbours, air, block = Block{minecraft:air}
←[m←[32m[19:47:24] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:grass_path}
←[m←[32m[19:47:24] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:47:24] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:47:24] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:47:24] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:47:24] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:48:32] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:56]: == notifyneighbours, air, block = Block{lightestlamp:light_air}
←[m←[32m[19:48:32] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{minecraft:grass_path}
←[m←[32m[19:48:32] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:48:32] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:48:32] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:48:32] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m←[32m[19:48:32] [Server thread/INFO] [STDOUT/]: [net.olafkeijsers.fastleafdecay.FastLeafDecay:notifyNeighbors:61]: ==== checking block = Block{lightestlamp:light_air}
←[m

**Comment by Olafski** [comment]
Apologies, no idea how those statements got back there. I released version 25 which should alleviate your spam issues.

Thanks for the report!
