### ISSUE TITLE
[1.15.2] FastLeafDecay v22 crash when Create Schematics are used on dedicated server.

### ISSUE THREAD

**Issue by Vaelzan** [Olafski/FastLeafDecay#41]
As per title.

Crash Report:
https://gist.github.com/Vaelzan/b346fe8050bcec4da23bff7cc11ef6c6

You should not be casting something that is not a ServerWorld to a ServerWorld in FldScheduler.tick.

**Comment by Olafski** [comment]
Thanks for the feedback Vaelzan. Good point, I should not be doing that. To be honest it's a struggle for me to make even this simple mod with every new version of Forge... 

I'll try to get a new version for 1.15 out soon, hopefully tomorrow.

**Comment by Vaelzan** [comment]
Thanks @Olafski I really do appreciate it. For now I've removed the mod but it's such a nice quality of life mod that I'm hoping I can add it back soon. :)

**Comment by Olafski** [comment]
I uploaded version 22.1. In that I check whether the World is a ServerWorld before even adding the update to the schedule. Hope that fixes your issue, please let me know. :)

**Comment by Olafski** [comment]
@Vaelzan any update on this, so I can mark the file as Release instead of Beta?
