### ISSUE TITLE
Warped wart blocks don't decay

### ISSUE THREAD

**Issue by kedamono** [Olafski/FastLeafDecay#43]
In the Nether, when you cut down a Warped Stem, the Warped Wart Blocks and Shroomlights don't decay. It's a pain to go up and break all the wart blocks with a hoe all the time. Can you add Wart Blocks to the list of things that decay?

**Comment by Olafski** [comment]
Hey kedamono, thanks for raising this issue. Unfortunately I can not do this. The way this mod works is that it works off of the normal decay of leaf blocks. I can not add random blocks to a list since those blocks don't have an update tick method that decays them. :(
