### ISSUE TITLE
FastLeafDecay isn't compatible with The Abyss Chapter II

### ISSUE THREAD

**Issue by Auseawesome** [Olafski/FastLeafDecay#45]
Fast Leaf Decay tries to find a persistent value in the Blueberry Leaves block but it doesn't have one. Game crashes when loading dimension.

**Comment by iobiarg** [comment]
Getting hard crash due this...

**Comment by TelepathicGrunt** [comment]
@Auseawesome you are most likely using Rapid Leaf Decay which crashes with Abyss Chapter II. Not Fast Leaf Decay. See my comment here:
https://github.com/Olafski/FastLeafDecay/issues/46#issuecomment-801939320

The crashlog states `at de.geheimagentnr1.rapid_leaf_decay.handlers.ForgeEventHandler.handleNeighborNotifyEvent(ForgeEventHandler.java:47) ~[rapid_leaf_decay:1.0.0]` which explicitly says rapid_leaf_decay and the exact property crash you mention
