### ISSUE TITLE
Incompatibility with Oh The Biomes You'll Go

### ISSUE THREAD

**Issue by tazzy989** [Olafski/FastLeafDecay#49]
Hi, I saw in the issue below mine that some other mods' leaves inherit the Block type instead of LeavesBlock type, where can I check that? I'm using OTBYG and fast leaf decay doesn't seem to apply to any of the modded trees. 

Thanks!

**Comment by Olafski** [comment]
Hey tazzy989, you'll need to check out the source code for the mod you're interested in. Find the leaves block that isn't behaving properly and see what it inherits from. (not sure if you're familiar with Java code, but that's near the top of the file, it should say something like `extends LeavesBlock`)

**Comment by SaphieNyako** [comment]
Extending on this issue. The Feywild mod also doesnt extend LeavesBlock cause we needed more options. Would it be possible to make a tag for this mod where we can add blocks wich will also count? Thanks :)

**Comment by Olafski** [comment]
I just released new versions of FastLeafDecay for a bunch of Minecraft versions. Checked with both OTBYG and Feywild and their leaves are both being decayed faster now!
