### ISSUE TITLE
1.10.2 requires mod on client side as well

### ISSUE THREAD

**Issue by maxpowa** [Olafski/FastLeafDecay#5]
Clients must have the mod or they get rejected from connecting to servers running the mod. Nothing stands out in the logs, just the standard FML mod rejections.

 ![img](https://u.xpw.us/zkmin6.png)

**Comment by Olafski** [comment]
Thanks for the report, I'll check it out asap!

**Comment by Olafski** [comment]
I uploaded a new version to curse (v11) which should fix this problem. Please let me know if you have any other issues and thanks again for the report!
