### ISSUE TITLE
Mod Licensing

### ISSUE THREAD

**Issue by jrddunbr** [Olafski/FastLeafDecay#50]
Hi,

On your GitHub here you have the MIT license.

On CurseForge it appears that you have set the mod to "All Rights Reserved". [link](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)

Is that a mistake?

Thanks!

**Comment by Olafski** [comment]
Hi jrddunbr,

Thanks for notifying me. I actually don't really use this repository except for issues. I'll remove all of the code and the license file when I have some time. :)
