### ISSUE TITLE
Singleplayer 1.17.1

### ISSUE THREAD

**Issue by Joskva** [Olafski/FastLeafDecay#51]
Hello,

i downloaded the mod for my singleplayer world. I also have more mods installed. But i does not work on any of my worlds, also a fully new generated and i dont have any config file.

Is there anything i forgot or anything i need to do?

Thank You in Advance

**Comment by Olafski** [comment]
Hey Joskva,

Which version of Forge are you using? I tried this two days ago when I developed the mod, using Forge 37.0.2 and it worked for that version.

**Comment by Olafski** [comment]
Feel free to reopen this if you want to continue the issue.

**Comment by Heisenbean** [comment]
forge version : 37.0.52
game version : 1.71.1
mod version : 26
play version : MacX OS 11.4
not work
help please
