### ISSUE TITLE
incompatibility with modded trees 

### ISSUE THREAD

**Issue by Andrezinho1** [Olafski/FastLeafDecay#54]
so far i've tested this with the pyromancer mod and in tropicraft but the trees aren't decaying let alone fast. is there a way we could get a config to add certain leaves to the list so they work with this mod

**Comment by Olafski** [comment]
Hi Andrezinho1, I just released a new version of FastLeafDecay which does additional checks for modded leaves.

With that, I tested Pyromancer and Tropicraft. Pyromancer trees don't naturally decay at all, so my mod can't improve the decay rates. 

Tropicraft is a little different. The "normal" trees decay just fine, the larger ones (Mahogany and Palm) don't decay naturally so again those are not affected by my mod either.
