### ISSUE TITLE
Check for membership in "leaves" block tag instead of extending LeavesBlock

### ISSUE THREAD

**Issue by daedalus4096** [Olafski/FastLeafDecay#56]
Hello, and thank you for developing such a useful mod!  I'm the developer of another mod called Primal Magick, and I just received a [ticket](https://github.com/daedalus4096/PrimalMagick/issues/59) about an incompatibility with your mod.  Specifically, I have a pair of leaf-like blocks that, for various technical reasons, don't derive from LeavesBlock and thus aren't detected by your mod.  They are, however, members of the "leaves" block tag that vanilla defines.  I understand if you don't want to change how your mod works because some rando asked you to, but if you were to check membership in that tag instead of or in addition to the instanceof check, I believe it would fix that incompatibility.  Thank you, and happy holidays!

**Comment by Olafski** [comment]
Hey daedalus4096, thanks for your comment. I have received this request in the past, and will try to get to it this Christmas holiday. I'll keep you posted via this ticket. :)

**Comment by Olafski** [comment]
Hey daedalus4096,

I made a new version for Minecraft 1.17.1: https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay/files/3587103

Seems to work with your mod. Could you verify this? If it works, I'll promote it to release version and make updates for the other minecraft versions I can still support as well ;-)

**Comment by daedalus4096** [comment]
I just tested the version you linked and it works great!  Thank you so much, and happy new year!

**Comment by Olafski** [comment]
Excellent! I will get to creating versions for the other Minecraft versions asap.

And happy new year as well :-)

**Comment by Olafski** [comment]
Older versions have been released, hope this provides the additional compatibility to other mods as well. :)
