### ISSUE TITLE
1.9/1.10 source (and 1.11 update)

### ISSUE THREAD

**Issue by HoldYourWaffle2** [Olafski/FastLeafDecay#6]
So I could update this mod to 1.11 so I can get it reeeaaally quick for my server (well once forge fully updates), but where's the source for 1.9/1.10?

**Comment by Olafski** [comment]
I'll try to get a 1.11 version available this weekend!

**Comment by Olafski** [comment]
You can download the 1.11 version at https://minecraft.curseforge.com/projects/fastleafdecay (it's v12).

I'll see what I can do about the sources at some later point... :)

**Comment by HoldYourWaffle2** [comment]
Well that was quick 🐑 💨
